export const allEpisodes = [
  "Building a Course",
  "SVGs FTW",
  "Crossover Episode with Purrfect Dev",
  "Getting git",
  "Small Design Tweaks that Make All the Difference",
  "Getting Started with TypeScript",
  "Struggle Bus",
  "Wordpress in 2021",
  "Freelancing IRL: Unveiling a Site Redesign",
  "Our Favorite Things: A Crossover Episode with Web Dev Weekly",
  "Talking to Some of Our Favorite Content Creators",
  "How Blogging Can Change Your Career",
  "Starting your own Podcast",
  "Getting Started on YouTube",
  "IRL Freelance Proposal",
  "Hiring a Designer or Getting Your First UI / UX Job",
  "Getting Your First Dev Job",
  "Learning and Building in Public",
  "Figma for Everyone",
  "Amy Gives James a Design Consult",
  "All Things Automated",
  "Live Streaming for Beginners",
  "Everything You Need to Know to Get Started in SvelteKit",
  "Building the Perfect Desk Setup",
  "The Future of Code with No Code",
  "Productivity: Tools, Tips, and Workflows",
  "Design Fundamentals (Part 2)",
  "Design Fundamentals (Part 1)",
  "The Tech Behind SelfTeach.me",
  "The Tech Behind jamesqquick.com",
  "Freelancing (Part 2)",
  "Freelancing (Part 1)",
  "How Do you Start a New Design Project?",
  "Starting a New Development Project",
  "The Tech Behind Compressed.fm",
  "Amy Dutton's Origin Story",
  "James Q Quick's Origin Story",
  "Trailer",
];

// [
//   ...document.querySelector(".EpisodeGrid__StyledEpisodeGrid-sc-1hlv0yk-0")
//     .children,
// ].map((article) => {
//   return article.children[1].innerText;
// });
